name: Telegram Test

on:
  workflow_dispatch:
    inputs:
      text:
        description: "Message to send"
        required: false
        default: "Hello from GitHub Actions 👋"

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        run: |
          curl -sS "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            --data-urlencode "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            --data-urlencode "text=${{ github.event.inputs.text }}"
